# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/jupyterlab-openbayes-bindings"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/jupyterlab-openbayes-dataset-browser"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/jupyterlab-openbayes-filebrowser-overwrite"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/jupyterlab-openbayes-introduction"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/jupyterlab-openbayes-snippets"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/jupyterlab-openbayes-task"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/jupyterlab-openbayes-theme"
    schedule:
      interval: "daily"
